#!/data/data/com.termux/files/usr/bin/sh
cd "$HOME/bahasaku" || exit 1
sh build.sh >/dev/null || { echo "build GAGAL"; exit 1; }
gagal=0
cek() {
  if [ "$2" = "$3" ]; then echo "OK    $1"
  else echo "GAGAL $1 (dapat '$2', harapan '$3')"; gagal=1; fi
}
H=bin/hex0
cek "hex0 huruf besar"   "$(echo '48 69' | $H)"                  "Hi"
cek "hex0 huruf kecil"   "$(echo '6a 6B' | $H)"                  "jk"
cek "hex0 komentar"      "$(printf '41 # abc 42 43\n44\n' | $H)" "AD"
cek "hex0 byte 00 FF"    "$(printf '00 FF 10' | $H | od -An -tx1 | tr -d ' \n')" "00ff10"
cek "ukuran halo"        "$(wc -c < bin/halo | tr -d ' ')"       "157"
cek "output halo"        "$(bin/halo)"                           "Halo"
B=bin/bk
sh tes-blok.sh || gagal=1
cek "bk hitung mundur"   "$($B contoh/mundur.bk | tr '\n' ' ')"  "5 4 3 2 1 "
cek "bk aritmetika"      "$($B contoh/hitung.bk | tr '\n' ' ')"  "14 10 -5 -14 "
cek "bk teks"            "$($B contoh/teks.bk | tr '\n' '|')"    "Halo dunia|x=7|"
cek "bk faktorial"       "$($B contoh/faktorial.bk)"             "120"
cek "bk perbandingan"    "$($B contoh/banding.bk)"               "benar"
cek "bk gosub"           "$($B contoh/sub.bk | tr '\n' ' ')"     "9 4 1 selesai "
cek "bk sisa bagi"       "$($B contoh/sisa.bk | tr '\n' ' ')"    "2 -1 "
cek "bk fizzbuzz"        "$($B contoh/fizzbuzz.bk | tr '\n' ' ')" "1 2 Fizz 4 Buzz Fizz 7 8 Fizz Buzz 11 Fizz 13 14 FizzBuzz "
cek "bk untuk"           "$($B contoh/untuk.bk | tr '\n' ' ')"   "1 4 9 16 25 "
cek "bk untuk bersarang" "$($B contoh/segitiga.bk | tr '\n' '|')" "*|**|***|"
cek "bk langkah mundur"  "$($B contoh/mundur2.bk | tr '\n' ' ')" "10 7 4 1 "
cek "bk loop nol kali"   "$($B contoh/nol.bk)"                   "benar"
cek "bk jika gosub"      "$($B contoh/jikagosub.bk | tr '\n' '|')" "besar|akhir|"
cek "bk prima"           "$($B contoh/prima.bk | tr '\n' ' ')"   "2 3 5 7 11 13 17 19 23 29 "
T=$(mktemp)
printf '10 BACA A\n20 TULIS A + 1\n' > "$T"
cek "bk baca input"      "$(echo 41 | $B "$T")"                  "42"
printf '10 ? 5\n' > "$T"
cek "bk pesan error"     "$($B "$T" 2>&1 | head -c 5)"           "error"
printf '10 KEMBALI\n' > "$T"
cek "bk kembali tanpa gosub" "$($B "$T" 2>&1 | head -c 5)"       "error"
printf '10 LANJUT\n' > "$T"
cek "bk lanjut tanpa untuk"  "$($B "$T" 2>&1 | head -c 5)"       "error"
rm -f "$T"
cek "bk prioritas operator" "$($B contoh/prioritas.bk | tr '\n' ' ')" "14 20 85 13 1 -5 "
cek "bk array"              "$($B contoh/array.bk | tr '\n' ' ')"     "0 1 4 9 16 "
cek "bk urut (bubble sort)" "$($B contoh/urut.bk | tr '\n' ' ')"      "1 2 5 7 9 "
T2=$(mktemp)
printf '10 A = 5 / 0\n' > "$T2"
cek "bk bagi nol"           "$($B "$T2" 2>&1 | head -c 5)"            "error"
printf '10 D(100) = 1\n' > "$T2"
cek "bk indeks di luar"     "$($B "$T2" 2>&1 | head -c 5)"            "error"
printf '10 TULIS (1 + 2\n' > "$T2"
cek "bk kurung tak tutup"   "$($B "$T2" 2>&1 | head -c 5)"            "error"
rm -f "$T2"
cek "bk abs"             "$($B contoh/fungsi.bk | tr '\n' ' ')"   "7 8 5 "
cek "bk acak rentang"    "$($B contoh/acak1.bk)"                  "0"
cek "bk acak bervariasi" "$($B contoh/acak2.bk)"                  "bervariasi"
cek "bk tebak angka"     "$(seq 1 100 | timeout 5 $B contoh/tebak.bk | tail -n 1)" "Benar!"
T3=$(mktemp)
printf '10 BACA D(2)\n20 TULIS D(2) + 1\n' > "$T3"
cek "bk baca ke array"   "$(printf '41\n' | $B "$T3")"            "42"
cek "bk baca array neg"  "$(printf -- '-5\n' | $B "$T3")"         "-4"
printf '10 A = ACAK(0)\n' > "$T3"
cek "bk acak nol"        "$($B "$T3" 2>&1 | head -c 5)"           "error"
printf '10 A = XY(1)\n' > "$T3"
cek "bk fungsi asing"    "$($B "$T3" 2>&1 | head -c 5)"           "error"
rm -f "$T3"
cek "bk string gabung"     "$($B contoh/string.bk | tr '\n' '|')"     "Halo, Budi|Budi dan Ani|x=10|"
cek "bk string jika"       "$($B contoh/strjika.bk)"                  "sama"
cek "bk string jika gosub" "$($B contoh/strgosub.bk | tr '\n' '|')"   "masuk|akhir|"
cek "bk string baca (=)"   "$(echo Budi | $B contoh/sapa.bk)"         "Nama kamu? Halo bos!"
cek "bk string baca (<>)"  "$(echo Ani | $B contoh/sapa.bk)"          "Nama kamu? Halo, Ani"
T4=$(mktemp)
printf '10 TULIS "a"; "b"; 1 + 2\n' > "$T4"
cek "bk tulis beberapa"    "$($B "$T4")"                              "ab3"
printf '10 A$ = "abc\n' > "$T4"
cek "bk teks tak tertutup" "$($B "$T4" 2>&1 | head -c 5)"             "error"
rm -f "$T4"
cek "bk fungsi teks angka" "$($B contoh/teksfn.bk | tr '\n' ' ')"    "10 65 124 3 0 "
cek "bk potong teks"       "$($B contoh/potong.bk | tr '\n' '|')"    "Sel|pagi|mat|Hi|-45!|"
cek "bk batas potong"      "$($B contoh/batas.bk | tr '\n' '|')"     "abc|abc|bc|[]||"
cek "bk jika fungsi teks"  "$($B contoh/strfn.bk | tr '\n' '|')"     "cocok|panjang|"
cek "bk balik teks"        "$(echo abc | $B contoh/balik.bk)"        "Kata: cba"
T5=$(mktemp)
printf '10 TULIS ANGKA("-42") + 2\n' > "$T5"
cek "bk angka negatif"     "$($B "$T5")"                             "-40"
printf '10 TULIS PANJANG(5)\n' > "$T5"
cek "bk panjang bukan teks" "$($B "$T5" 2>&1 | head -c 5)"           "error"
printf '10 A$ = FOO$(1)\n' > "$T5"
cek "bk fungsi teks asing" "$($B "$T5" 2>&1 | head -c 5)"            "error"
printf '10 A$ = KIRI$("abc")\n' > "$T5"
cek "bk kiri tanpa koma"   "$($B "$T5" 2>&1 | head -c 5)"            "error"
rm -f "$T5"
BK="$PWD/bin/bk"; C="$PWD/contoh"; FD=$(mktemp -d)
cek "bk file tulis & baca"  "$(cd "$FD" && "$BK" "$C/tulisfile.bk" | tr '\n' '|')" "[baris satu]|[angka 42]|[tanpa-nl]|"
cek "bk isi file"           "$(tr '\n' '|' < "$FD/uji.txt")"                      "baris satu|angka 42|tanpa-nl|"
cek "bk file mode tambah"   "$(cd "$FD" && "$BK" "$C/tambah.bk" | tr '\n' '|')"   "a|b|"
cek "bk file kosong"        "$(cd "$FD" && "$BK" "$C/kosong.bk")"                 "1"
printf '10 BUKA 1, "tidak-ada.txt", "r"\n' > "$FD/e1.bk"
cek "bk buka file tak ada"  "$(cd "$FD" && "$BK" e1.bk 2>&1 | head -c 5)"         "error"
printf '10 BUKA 9, "x", "r"\n' > "$FD/e2.bk"
cek "bk nomor file salah"   "$(cd "$FD" && "$BK" e2.bk 2>&1 | head -c 5)"         "error"
printf '10 TUTUP 3\n20 TULIS "ok"\n' > "$FD/e3.bk"
cek "bk tutup tanpa buka"   "$(cd "$FD" && "$BK" e3.bk 2>&1)"                     "ok"
printf '10 TULISFILE 2, "x"\n' > "$FD/e4.bk"
cek "bk tulis file tertutup" "$(cd "$FD" && "$BK" e4.bk 2>&1 | head -c 5)"        "error"
cek "bk buku tamu"          "$(cd "$FD" && echo Budi | "$BK" "$C/bukutamu.bk" >/dev/null; echo Ani | "$BK" "$C/bukutamu.bk" | tr '\n' '|')" "Nama kamu? Daftar tamu:|- Budi|- Ani|"
rm -rf "$FD"
cek "bk lompat cepat"      "$(timeout 20 $B contoh/cepat.bk)"        "100000"
cek "bk nomor baris dobel" "$($B contoh/dobel.bk | tr '\n' '|')"     "pertama|kedua|"
cek "bk nomor baris besar" "$($B contoh/besar.bk)"                   "ok"
T6=$(mktemp)
printf '10 LOMPAT 77\n' > "$T6"
cek "bk baris tak ada"     "$($B "$T6" 2>&1 | head -c 5)"            "error"
rm -f "$T6"
cek "bk label ulang"        "$($B contoh/label1.bk | tr '\n' ' ')"   "3 2 1 selesai "
cek "bk label gosub"        "$($B contoh/label2.bk | tr '\n' '|')"   "hai|hai|akhir|"
cek "bk label maju & huruf" "$($B contoh/label3.bk)"                 "ok"
cek "bk label campur nomor" "$($B contoh/label4.bk | tr '\n' '|')"   "3|ok|"
cek "bk label jika gosub"   "$($B contoh/label5.bk | tr '\n' '|')"   "besar|akhir|"
T7=$(mktemp)
printf 'LOMPAT nada\n' > "$T7"
cek "bk label tak ada"      "$($B "$T7" 2>&1 | head -c 5)"           "error"
printf 'GOSUB nada\n' > "$T7"
cek "bk gosub label tak ada" "$($B "$T7" 2>&1 | head -c 5)"          "error"
printf 'LOMPAT dup\nTULIS "salah"\nLABEL dup\nTULIS "pertama"\nBERHENTI\nLABEL dup\nTULIS "kedua"\n' > "$T7"
cek "bk label dobel"        "$($B "$T7" | tr '\n' '|')"              "pertama|"
{ echo 'TULIS "mulai"'; echo 'LOMPAT L64'; echo 'TULIS "salah"'; seq 1 64 | sed 's/^/LABEL L/'; echo 'TULIS "ok"'; } > "$T7"
cek "bk 64 label"           "$($B "$T7" | tr '\n' '|')"              "mulai|ok|"
{ seq 1 65 | sed 's/^/LABEL L/'; echo 'LOMPAT L1'; } > "$T7"
cek "bk label kebanyakan"   "$($B "$T7" 2>&1 | head -c 5)"           "error"
rm -f "$T7"
cek "bk include subrutin"   "$($B contoh/pakai.bk | tr '\n' '|')"    "49|halo dari lib|selesai|"
cek "bk include tak jatuh"  "$($B contoh/pakai2.bk | tr '\n' '|')"   "awal|akhir|"
cek "bk include nomor baris" "$($B contoh/pakai3.bk | tr '\n' '|')"  "angka|ok|"
T8=$(mktemp)
printf 'INCLUDE "contoh/lib.bk"\nA = 3\nGOSUB kuadrat\nTULIS R' > "$T8"
cek "bk include tanpa newline" "$($B "$T8")"                         "9"
printf 'INCLUDE "contoh/lib.bk"\nINCLUDE "contoh/lib.bk"\nA = 2\nGOSUB kuadrat\nTULIS R\n' > "$T8"
cek "bk include dua kali"   "$($B "$T8")"                            "4"
printf 'N$ = "contoh/lib.bk"\nINCLUDE N$\nA = 4\nGOSUB kuadrat\nTULIS R\n' > "$T8"
cek "bk include dari variabel" "$($B "$T8")"                         "16"
printf 'INCLUDE "tidak/ada.bk"\n' > "$T8"
cek "bk include file tak ada" "$($B "$T8" 2>&1 | head -c 5)"         "error"
printf 'INCLUDE\n' > "$T8"
cek "bk include tanpa nama" "$($B "$T8" 2>&1 | head -c 5)"           "error"
rm -f "$T8"
cek "bk fungsi dasar"        "$($B contoh/fungsi1.bk | tr '\n' '|')"  "49|25|"
cek "bk fungsi rekursi"      "$($B contoh/fungsi2.bk | tr '\n' '|')"  "120|3628800|"
cek "bk fungsi fibonacci"    "$($B contoh/fungsi3.bk | tr '\n' '|')"  "55|"
cek "bk fungsi lokal"        "$($B contoh/fungsi4.bk | tr '\n' '|')"  "6|100|"
cek "bk fungsi banyak arg"   "$($B contoh/fungsi5.bk | tr '\n' '|')"  "7|15|0|"
cek "bk panggil"             "$($B contoh/fungsi6.bk | tr '\n' '|')"  "halo 3|halo 4|selesai|"
cek "bk fungsi loop lokal"   "$($B contoh/fungsi7.bk | tr '\n' '|')"  "4|5|6|"
cek "bk fungsi include"      "$($B contoh/pakaifn.bk | tr '\n' '|')"  "27|"
T9=$(mktemp)
printf 'HASIL 5\n' > "$T9"
cek "bk hasil di luar fungsi" "$($B "$T9" 2>&1 | head -c 5)"          "error"
printf 'TULIS tidakada(1)\n' > "$T9"
cek "bk fungsi tak ada"      "$($B "$T9" 2>&1 | head -c 5)"           "error"
printf 'FUNGSI lp(N)\nHASIL lp(N + 1)\nAKHIRFUNGSI\nTULIS lp(1)\n' > "$T9"
cek "bk rekursi tak berhenti" "$($B "$T9" 2>&1 | head -c 5)"          "error"
printf 'FUNGSI tb(A, B)\nHASIL A + B\nAKHIRFUNGSI\nTULIS tb(1, 2, 3, 4, 5)\n' > "$T9"
cek "bk argumen kebanyakan"  "$($B "$T9" 2>&1 | head -c 5)"           "error"
rm -f "$T9"
PD=$(mktemp -d)
cek "paket dibuat"           "$(sh paket.sh contoh/fizzbuzz.bk "$PD/fb" | head -c 6)"  "paket:"
cek "paket jalan mandiri"    "$("$PD/fb" | tr '\n' ' ')"  "1 2 Fizz 4 Buzz Fizz 7 8 Fizz Buzz 11 Fizz 13 14 FizzBuzz "
cek "paket abaikan argumen"  "$("$PD/fb" x y | head -n 1)"  "1"
cek "paket dari folder lain" "$(cd "$PD" && "$PD/fb" | tail -n 1)"  "FizzBuzz"
sh paket.sh contoh/fungsi3.bk "$PD/fib" >/dev/null
cek "paket fungsi"           "$("$PD/fib")"  "55"
sh paket.sh contoh/sapa.bk "$PD/sapa" >/dev/null
cek "paket baca input"       "$(echo Ani | "$PD/sapa")"  "Nama kamu? Halo, Ani"
sh paket.sh contoh/pakaifn.bk "$PD/inc" >/dev/null
cek "paket include"          "$("$PD/inc")"  "27"
cek "paket ukuran"           "$(wc -c < "$PD/fb" | tr -d ' ')"  "$(( $(wc -c < bin/bk) + $(wc -c < contoh/fizzbuzz.bk) + 16 ))"
cek "paket tanpa file"       "$(sh paket.sh tidak-ada.bk "$PD/x" 2>&1 | head -c 6)"  "paket:"
cek "bk biasa tanpa argumen" "$($B 2>&1 | head -c 5)"  "pakai"
rm -rf "$PD"
T10=$(mktemp)
printf 'A = 5\nB = A / 0\n' > "$T10"
cek "error nomor baris"      "$($B "$T10" 2>&1 | tail -n 1)"  "  pada baris 2: B = A / 0"
printf 'TULIS 1\nLOMPAT 77\n' > "$T10"
cek "error lompat baris"     "$($B "$T10" 2>&1 | tail -n 1)"  "  pada baris 2: LOMPAT 77"
printf 'LOMPAT tidakada\n' > "$T10"
cek "error label baris"      "$($B "$T10" 2>&1 | tail -n 1)"  "  pada baris 1: LOMPAT tidakada"
printf 'FUNGSI lp(N)\nHASIL lp(N + 1)\nAKHIRFUNGSI\nTULIS lp(1)\n' > "$T10"
cek "error rekursi baris"    "$($B "$T10" 2>&1 | tail -n 1)"  "  pada baris 2: HASIL lp(N + 1)"
printf 'A = [\n' > "$T10"
cek "error sintaks baris"    "$($B "$T10" 2>&1 | tail -n 1)"  "  pada baris 1: A = ["
printf 'TULIS 1\n\n\nD(500) = 3\n' > "$T10"
cek "error baris kosong"     "$($B "$T10" 2>&1 | tail -n 1)"  "  pada baris 4: D(500) = 3"
cek "error pesan lama utuh"  "$($B "$T10" 2>&1 | sed -n 2p)"  "error: indeks array harus 0-99"
sh paket.sh "$T10" "$T10.pk" >/dev/null
cek "error di paket mandiri" "$("$T10.pk" 2>&1 | tail -n 1)"  "  pada baris 4: D(500) = 3"
rm -f "$T10" "$T10.pk"
T11=$(mktemp)
printf 'X = 5\nKALAU X > 3\nTULIS "besar"\nLAIN\nTULIS "kecil"\nAKHIRKALAU\nTULIS "selesai"\n' > "$T11"
cek "kalau cabang benar"     "$($B "$T11" | tr '\n' '|')"  "besar|selesai|"
printf 'X = 1\nKALAU X > 3\nTULIS "besar"\nLAIN\nTULIS "kecil"\nAKHIRKALAU\nTULIS "selesai"\n' > "$T11"
cek "kalau cabang lain"      "$($B "$T11" | tr '\n' '|')"  "kecil|selesai|"
printf 'KALAU 1 > 2\nTULIS "a"\nAKHIRKALAU\nTULIS "b"\n' > "$T11"
cek "kalau salah tanpa lain" "$($B "$T11" | tr '\n' '|')"  "b|"
printf 'X = 5\nKALAU X > 3\nKALAU X > 10\nTULIS "sangat"\nLAIN\nTULIS "sedang"\nAKHIRKALAU\nLAIN\nTULIS "kecil"\nAKHIRKALAU\n' > "$T11"
cek "kalau bersarang"        "$($B "$T11" | tr '\n' '|')"  "sedang|"
printf 'I = 1\nSELAMA I <= 3\nTULIS I\nI = I + 1\nAKHIRSELAMA\nTULIS "tamat"\n' > "$T11"
cek "selama menghitung"      "$($B "$T11" | tr '\n' '|')"  "1|2|3|tamat|"
printf 'I = 9\nSELAMA I < 3\nTULIS I\nAKHIRSELAMA\nTULIS "x"\n' > "$T11"
cek "selama tak jalan"       "$($B "$T11" | tr '\n' '|')"  "x|"
printf 'I = 1\nSELAMA I <= 2\nJ = 1\nSELAMA J <= 2\nTULIS I * 10 + J\nJ = J + 1\nAKHIRSELAMA\nI = I + 1\nAKHIRSELAMA\n' > "$T11"
cek "selama bersarang"       "$($B "$T11" | tr '\n' '|')"  "11|12|21|22|"
printf 'FUNGSI kuadrat(X)\nHASIL X * X\nAKHIRFUNGSI\nI = 1\nSELAMA kuadrat(I) < 30\nKALAU I %% 2 = 0\nTULIS I\nAKHIRKALAU\nI = I + 1\nAKHIRSELAMA\n' > "$T11"
cek "selama kondisi fungsi"  "$($B "$T11" | tr '\n' '|')"  "2|4|"
printf 'A$ = "ya"\nKALAU A$ = "ya"\nTULIS "cocok"\nLAIN\nTULIS "beda"\nAKHIRKALAU\n' > "$T11"
cek "kalau teks"             "$($B "$T11" | tr '\n' '|')"  "cocok|"
printf 'I = 0\nSELAMA 1 = 1\nI = I + 1\nJIKA I = 3 LOMPAT keluar\nAKHIRSELAMA\nLABEL keluar\nTULIS I\n' > "$T11"
cek "selama lompat keluar"   "$($B "$T11" | tr '\n' '|')"  "3|"
printf 'FUNGSI mutlak(N)\nKALAU N < 0\nHASIL 0 - N\nAKHIRKALAU\nHASIL N\nAKHIRFUNGSI\nTULIS mutlak(0 - 7)\nTULIS mutlak(4)\n' > "$T11"
cek "hasil dalam kalau"      "$($B "$T11" | tr '\n' '|')"  "7|4|"
printf '10 X = 2\n20 KALAU X = 2\n30 TULIS "dua"\n40 AKHIRKALAU\n' > "$T11"
cek "kalau nomor baris"      "$($B "$T11" | tr '\n' '|')"  "dua|"
printf 'FUNGSI fakt(N)\nKALAU N <= 1\nHASIL 1\nAKHIRKALAU\nHASIL N * fakt(N - 1)\nAKHIRFUNGSI\nTULIS fakt(5)\n' > "$T11"
cek "kalau dalam rekursi"    "$($B "$T11" | tr '\n' '|')"  "120|"
printf 'FUNGSI ganda(N)\nKALAU N > 1\nHASIL N * 2\nAKHIRKALAU\nHASIL 0\nAKHIRFUNGSI\nKALAU ganda(3) = 6\nTULIS "enam"\nLAIN\nTULIS "bukan"\nAKHIRKALAU\n' > "$T11"
cek "kondisi panggil kalau"  "$($B "$T11" | tr '\n' '|')"  "enam|"
printf 'UNTUK I = 1 SAMPAI 5\nKALAU I = 3\nTULIS I\nAKHIRKALAU\nLANJUT\n' > "$T11"
cek "untuk dengan kalau"     "$($B "$T11" | tr '\n' '|')"  "3|"
printf 'KALAU 1 = 2\nTULIS 1\n' > "$T11"
cek "kalau tanpa pasangan"   "$($B "$T11" 2>&1 | tail -n 1)"  "  pada baris 1: KALAU 1 = 2"
printf 'TULIS 1\nAKHIRSELAMA\n' > "$T11"
cek "akhirselama yatim"      "$($B "$T11" 2>&1 | tail -n 1)"  "  pada baris 2: AKHIRSELAMA"
rm -f "$T11"
T12=$(mktemp)
printf 'FUNGSI sapa$(N)\nHASILTEKS "halo " + TEKS$(N)\nAKHIRFUNGSI\nTULIS sapa$(3)\n' > "$T12"
cek "fungsi teks dasar"      "$($B "$T12" | tr '\n' '|')"  "halo 3|"
printf 'FUNGSI sapa$(N)\nHASILTEKS "halo " + TEKS$(N)\nAKHIRFUNGSI\nA$ = sapa$(7)\nTULIS A$\n' > "$T12"
cek "fungsi teks tugas"      "$($B "$T12" | tr '\n' '|')"  "halo 7|"
printf 'FUNGSI sapa$(N)\nHASILTEKS "halo " + TEKS$(N)\nAKHIRFUNGSI\nB$ = "[" + sapa$(1) + "]"\nTULIS B$\n' > "$T12"
cek "fungsi teks gabung"     "$($B "$T12" | tr '\n' '|')"  "[halo 1]|"
printf 'FUNGSI ulang$(N)\nKALAU N <= 0\nHASILTEKS ""\nAKHIRKALAU\nHASILTEKS "ab" + ulang$(N - 1)\nAKHIRFUNGSI\nTULIS ulang$(3)\n' > "$T12"
cek "fungsi teks rekursi"    "$($B "$T12" | tr '\n' '|')"  "ababab|"
printf 'FUNGSI bintang$(N, I)\nT$ = ""\nUNTUK I = 1 SAMPAI N\nT$ = T$ + "*"\nLANJUT\nHASILTEKS T$\nAKHIRFUNGSI\nTULIS bintang$(5)\n' > "$T12"
cek "fungsi teks loop"       "$($B "$T12" | tr '\n' '|')"  "*****|"
printf 'FUNGSI sapa$(N)\nHASILTEKS "halo " + TEKS$(N)\nAKHIRFUNGSI\nKALAU sapa$(2) = "halo 2"\nTULIS "cocok"\nLAIN\nTULIS "beda"\nAKHIRKALAU\n' > "$T12"
cek "fungsi teks banding"    "$($B "$T12" | tr '\n' '|')"  "cocok|"
printf 'FUNGSI kosong$(N)\nAKHIRFUNGSI\nTULIS "["; kosong$(1); "]"\n' > "$T12"
cek "fungsi teks kosong"     "$($B "$T12" | tr '\n' '|')"  "[]|"
printf 'FUNGSI sapa$(N)\nHASILTEKS "halo " + TEKS$(N)\nAKHIRFUNGSI\nTULIS KIRI$(sapa$(5), 4)\n' > "$T12"
cek "fungsi teks dalam kiri" "$($B "$T12" | tr '\n' '|')"  "halo|"
printf 'FUNGSI sapa$(N)\nHASILTEKS "halo " + TEKS$(N)\nAKHIRFUNGSI\nFUNGSI dua$(N)\nHASILTEKS sapa$(N) + "!" + sapa$(N + 1)\nAKHIRFUNGSI\nTULIS dua$(4)\n' > "$T12"
cek "fungsi teks bertingkat" "$($B "$T12" | tr '\n' '|')"  "halo 4!halo 5|"
printf 'FUNGSI daftar$(N, I)\nR$ = ""\nI = 1\nSELAMA I <= N\nR$ = R$ + TEKS$(I)\nI = I + 1\nAKHIRSELAMA\nHASILTEKS R$\nAKHIRFUNGSI\nTULIS daftar$(5)\n' > "$T12"
cek "fungsi teks dlm selama" "$($B "$T12" | tr '\n' '|')"  "12345|"
printf 'N = 99\nFUNGSI nama$(N)\nHASILTEKS "x"\nAKHIRFUNGSI\nTULIS nama$(1)\nTULIS N\n' > "$T12"
cek "fungsi teks param pulih" "$($B "$T12" | tr '\n' '|')" "x|99|"
printf 'FUNGSI sapa$(N)\nHASILTEKS "halo " + TEKS$(N)\nAKHIRFUNGSI\nUNTUK I = 1 SAMPAI 3\nTULIS sapa$(I)\nLANJUT\n' > "$T12"
cek "fungsi teks dlm untuk"  "$($B "$T12" | tr '\n' '|')"  "halo 1|halo 2|halo 3|"
printf 'FUNGSI pj$(N)\nHASILTEKS "0123456789012345678901234567890123456789012345678901234567890123456789"\nAKHIRFUNGSI\nA$ = pj$(1)\nTULIS PANJANG(A$)\n' > "$T12"
cek "fungsi teks maks 63"    "$($B "$T12" | tr '\n' '|')"  "63|"
printf 'HASILTEKS "x"\n' > "$T12"
cek "hasilteks luar fungsi"  "$($B "$T12" 2>&1 | head -c 5)"  "error"
rm -f "$T12"
T13=$(mktemp)
printf 'FUNGSI sapa$(N$)\nHASILTEKS "halo " + N$\nAKHIRFUNGSI\nTULIS sapa$("Budi")\n' > "$T13"
cek "param teks dasar"       "$($B "$T13" | tr '\n' '|')"  "halo Budi|"
printf 'FUNGSI sapa$(N$)\nHASILTEKS "halo " + N$\nAKHIRFUNGSI\nA$ = "Ani"\nTULIS sapa$(A$)\n' > "$T13"
cek "param teks variabel"    "$($B "$T13" | tr '\n' '|')"  "halo Ani|"
printf 'FUNGSI sapa$(N$)\nHASILTEKS "halo " + N$\nAKHIRFUNGSI\nN$ = "asli"\nX$ = sapa$("lain")\nTULIS N$\n' > "$T13"
cek "param teks lokal pulih" "$($B "$T13" | tr '\n' '|')"  "asli|"
printf 'FUNGSI ulang$(S$, N, I, R$)\nUNTUK I = 1 SAMPAI N\nR$ = R$ + S$\nLANJUT\nHASILTEKS R$\nAKHIRFUNGSI\nR$ = "keep"\nTULIS ulang$("ab", 3)\nTULIS R$\n' > "$T13"
cek "param teks banyak lokal" "$($B "$T13" | tr '\n' '|')" "ababab|keep|"
printf 'FUNGSI balik$(S$)\nKALAU PANJANG(S$) <= 1\nHASILTEKS S$\nAKHIRKALAU\nHASILTEKS balik$(KANAN$(S$, PANJANG(S$) - 1)) + KIRI$(S$, 1)\nAKHIRFUNGSI\nTULIS balik$("abcd")\n' > "$T13"
cek "param teks rekursi"     "$($B "$T13" | tr '\n' '|')"  "dcba|"
printf 'FUNGSI hitung(S$)\nHASIL PANJANG(S$)\nAKHIRFUNGSI\nTULIS hitung("halo")\n' > "$T13"
cek "param teks fungsi angka" "$($B "$T13" | tr '\n' '|')" "4|"
printf 'FUNGSI kurung$(S$)\nHASILTEKS "[" + S$ + "]"\nAKHIRFUNGSI\nTULIS kurung$()\n' > "$T13"
cek "param teks arg kurang"  "$($B "$T13" | tr '\n' '|')"  "[]|"
printf 'FUNGSI sapa$(N$)\nHASILTEKS "halo " + N$\nAKHIRFUNGSI\nTULIS sapa$(sapa$("x"))\n' > "$T13"
cek "param teks bersarang"   "$($B "$T13" | tr '\n' '|')"  "halo halo x|"
printf 'FUNGSI sapa$(N$)\nHASILTEKS "halo " + N$\nAKHIRFUNGSI\nN$ = "dalam"\nTULIS sapa$(N$)\nTULIS N$\n' > "$T13"
cek "param teks nama sama"   "$($B "$T13" | tr '\n' '|')"  "halo dalam|dalam|"
printf 'FUNGSI ke$(N, S$)\nHASILTEKS TEKS$(N) + S$\nAKHIRFUNGSI\nTULIS ke$(5, "x")\n' > "$T13"
cek "param teks campur"      "$($B "$T13" | tr '\n' '|')"  "5x|"
printf 'FUNGSI dua$(A$, B$)\nHASILTEKS A$ + "/" + B$\nAKHIRFUNGSI\nA$ = "g1"\nB$ = "g2"\nTULIS dua$("x", "y")\nTULIS A$; B$\n' > "$T13"
cek "param teks dua global"  "$($B "$T13" | tr '\n' '|')"  "x/y|g1g2|"
printf 'FUNGSI jumlah$(N, S$)\nKALAU N = 0\nHASILTEKS "ok"\nAKHIRKALAU\nHASILTEKS jumlah$(N - 1, S$)\nAKHIRFUNGSI\nTULIS jumlah$(60, "x")\n' > "$T13"
cek "param teks rekursi 60"  "$($B "$T13" | tr '\n' '|')"  "ok|"
printf 'FUNGSI sapa$(N$)\nHASILTEKS "halo " + N$\nAKHIRFUNGSI\nTULIS sapa$(5)\n' > "$T13"
cek "param teks salah tipe"  "$($B "$T13" 2>&1 | head -c 5)"  "error"
printf 'FUNGSI fib(N)\nKALAU N < 2\nHASIL N\nAKHIRKALAU\nHASIL fib(N - 1) + fib(N - 2)\nAKHIRFUNGSI\nTULIS fib(10)\n' > "$T13"
cek "fungsi angka tetap"     "$($B "$T13" | tr '\n' '|')"  "55|"
rm -f "$T13"
T14=$(mktemp)
printf 'siswa.umur = 17\nTULIS siswa.umur\n' > "$T14"
cek "rekaman angka"          "$($B "$T14" | tr '\n' '|')"  "17|"
printf 'siswa.nama$ = "Ani"\nTULIS siswa.nama$\n' > "$T14"
cek "rekaman teks"           "$($B "$T14" | tr '\n' '|')"  "Ani|"
printf 'siswa.umur = 17\nsiswa.umur = siswa.umur + 1\nTULIS siswa.umur * 2\n' > "$T14"
cek "rekaman hitung"         "$($B "$T14" | tr '\n' '|')"  "36|"
printf 'siswa.nama$ = "Ani"\nsiswa.salam$ = "Halo " + siswa.nama$ + "!"\nTULIS siswa.salam$\n' > "$T14"
cek "rekaman gabung teks"    "$($B "$T14" | tr '\n' '|')"  "Halo Ani!|"
printf 'UNTUK I = 1 SAMPAI 3\nsiswa.umur(I) = I * 10\nsiswa.nama$(I) = "N" + TEKS$(I)\nLANJUT\nTULIS siswa.umur(2); " "; siswa.nama$(3)\n' > "$T14"
cek "rekaman berindeks"      "$($B "$T14" | tr '\n' '|')"  "20 N3|"
printf 'ayah.umur = 40\nanak.umur = 10\nTULIS ayah.umur - anak.umur\n' > "$T14"
cek "rekaman dua nama"       "$($B "$T14" | tr '\n' '|')"  "30|"
printf 'TULIS siswa.kosong\nTULIS "["; siswa.teks$; "]"\n' > "$T14"
cek "rekaman kosong"         "$($B "$T14" | tr '\n' '|')"  "0|[]|"
printf 'siswa.umur = 17\nsiswa.nama$ = "Ani"\nKALAU siswa.umur > 10\nTULIS "besar"\nAKHIRKALAU\nKALAU siswa.nama$ = "Ani"\nTULIS "ani"\nAKHIRKALAU\n' > "$T14"
cek "rekaman kondisi"        "$($B "$T14" | tr '\n' '|')"  "besar|ani|"
printf 'Siswa.Umur = 5\nTULIS siswa.umur\n' > "$T14"
cek "rekaman huruf besar"    "$($B "$T14" | tr '\n' '|')"  "5|"
printf 'siswa.nama$ = "Ani"\nsiswa.umur = 17\nTULIS siswa.nama$; " "; siswa.umur\n' > "$T14"
cek "rekaman tulis campur"   "$($B "$T14" | tr '\n' '|')"  "Ani 17|"
printf 'FUNGSI tambah(N)\nsiswa.umur = siswa.umur + N\nHASIL siswa.umur\nAKHIRFUNGSI\nsiswa.umur = 10\nTULIS tambah(5)\nTULIS siswa.umur\n' > "$T14"
cek "rekaman dalam fungsi"   "$($B "$T14" | tr '\n' '|')"  "15|15|"
printf 'FUNGSI ambil$(I)\nHASILTEKS siswa.nama$(I)\nAKHIRFUNGSI\nsiswa.nama$(2) = "Budi"\nTULIS ambil$(2)\n' > "$T14"
cek "rekaman hasilteks"      "$($B "$T14" | tr '\n' '|')"  "Budi|"
printf 'siswa.nama$ = "Ani"\nsiswa.nama$ = siswa.nama$ + "x"\nTULIS siswa.nama$\n' > "$T14"
cek "rekaman timpa teks"     "$($B "$T14" | tr '\n' '|')"  "Anix|"
printf 'UNTUK I = 1 SAMPAI 4\nnilai.skor(I) = I * 5\nLANJUT\nT = 0\nUNTUK I = 1 SAMPAI 4\nT = T + nilai.skor(I)\nLANJUT\nTULIS T\n' > "$T14"
cek "rekaman daftar"         "$($B "$T14" | tr '\n' '|')"  "50|"
printf 'UNTUK I = 1 SAMPAI 520\ntab.x(I) = I\nLANJUT\n' > "$T14"
cek "rekaman penuh"          "$($B "$T14" 2>&1 | head -c 5)"  "error"
printf 'tab.x(0 - 1) = 5\n' > "$T14"
cek "rekaman indeks negatif" "$($B "$T14" 2>&1 | head -c 5)"  "error"
printf 'TULIS "a.b"\n' > "$T14"
cek "titik dalam string aman" "$($B "$T14" | tr '\n' '|')" "a.b|"
rm -f "$T14"
T15=$(mktemp)
printf 'jumlah = 5\nTULIS jumlah\n' > "$T15"
cek "variabel panjang angka"    "$($B "$T15" | tr '\n' '|')"  "5|"
printf 'jumlah = 5\njumlah = jumlah + 1\nTULIS jumlah * 2\n' > "$T15"
cek "variabel panjang hitung"   "$($B "$T15" | tr '\n' '|')"  "12|"
printf 'nama$ = "Ani"\nTULIS nama$\n' > "$T15"
cek "variabel panjang teks"     "$($B "$T15" | tr '\n' '|')"  "Ani|"
printf 'nama$ = "Ani"\nsalam$ = "Halo " + nama$ + "!"\nTULIS salam$\n' > "$T15"
cek "variabel panjang gabung"   "$($B "$T15" | tr '\n' '|')"  "Halo Ani!|"
printf 'jumlah = 5\nnama$ = "Ani"\nKALAU jumlah > 3\nTULIS "besar"\nAKHIRKALAU\nKALAU nama$ = "Ani"\nTULIS "ani"\nAKHIRKALAU\n' > "$T15"
cek "variabel panjang kondisi"  "$($B "$T15" | tr '\n' '|')"  "besar|ani|"
printf 'BACA nama$\nTULIS "Halo, "; nama$\n' > "$T15"
cek "variabel panjang baca teks" "$(printf 'Ani\n' | $B "$T15" | tr '\n' '|')"  "Halo, Ani|"
printf 'BACA umur\nTULIS umur + 1\n' > "$T15"
cek "variabel panjang baca angka" "$(printf '17\n' | $B "$T15" | tr '\n' '|')"  "18|"
printf 'total = 0\nUNTUK I = 1 SAMPAI 5\ntotal = total + I\nLANJUT\nTULIS total\n' > "$T15"
cek "variabel panjang loop"     "$($B "$T15" | tr '\n' '|')"  "15|"
printf 'FUNGSI tambah(N)\ntotal = total + N\nHASIL total\nAKHIRFUNGSI\ntotal = 10\nTULIS tambah(5)\n' > "$T15"
cek "variabel panjang fungsi"   "$($B "$T15" | tr '\n' '|')"  "15|"
printf 'FUNGSI hitung(N)\nHASIL N * 2\nAKHIRFUNGSI\nhitung = 7\nTULIS hitung + hitung(3)\n' > "$T15"
cek "variabel dan fungsi sama nama" "$($B "$T15" | tr '\n' '|')" "13|"
printf 'TULIS belum\nTULIS "["; kosong$; "]"\n' > "$T15"
cek "variabel panjang kosong"  "$($B "$T15" | tr '\n' '|')"  "0|[]|"
printf 'Jumlah = 4\nTULIS jumlah\n' > "$T15"
cek "variabel panjang huruf besar" "$($B "$T15" | tr '\n' '|')" "4|"
printf 'J = 1\njumlah = 9\nTULIS J\n' > "$T15"
cek "variabel panjang vs tunggal" "$($B "$T15" | tr '\n' '|')" "1|"
printf 'D(3) = 7\nidx = 3\nTULIS D(idx)\n' > "$T15"
cek "variabel panjang indeks"   "$($B "$T15" | tr '\n' '|')"  "7|"
printf 'siswa.umur = 3\numur = 5\nTULIS siswa.umur + umur\n' > "$T15"
cek "variabel panjang rekaman"  "$($B "$T15" | tr '\n' '|')"  "8|"
printf 'jumlah = 5\nJIKA jumlah = 5 LOMPAT ok\nTULIS "salah"\nBERHENTI\nLABEL ok\nTULIS "benar"\n' > "$T15"
cek "variabel panjang jika"     "$($B "$T15" | tr '\n' '|')"  "benar|"
printf 'nama$ = "Ani"\nnama$ = nama$ + "x"\nTULIS nama$\n' > "$T15"
cek "variabel panjang timpa teks" "$($B "$T15" | tr '\n' '|')" "Anix|"
printf 'item2 = 4\nTULIS item2\n' > "$T15"
cek "variabel panjang digit"    "$($B "$T15" | tr '\n' '|')"  "4|"
printf 'abcdefghijklmnopqrstuvwxyzabc = 1\n' > "$T15"
cek "variabel panjang kepanjangan" "$($B "$T15" 2>&1 | head -c 5)" "error"
printf 'nama$ = "Ani"\numur = 17\nTULIS nama$; " "; umur\n' > "$T15"
cek "variabel panjang tulis banyak" "$($B "$T15" | tr '\n' '|')" "Ani 17|"
rm -f "$T15"
RD=$(mktemp -d)
RK="$RD/hexbk"
sh rakit.sh src/hex0.s "$RK" >/dev/null 2>&1
cek "rakit ukuran hex0"      "$(wc -c < "$RK" | tr -d ' ')"  "396"
cek "rakit hex0 jalan"       "$(printf '48 65 6c 6c 6f' | "$RK")"  "Hello"
cek "rakit hex0 bootstrap"   "$("$RK" < seed/hex0.hex | cksum)"  "$(bin/hex0 < seed/hex0.hex | cksum)"
printf '_start:\n    mov x0, #7\n    mov x8, #93\n    svc #0\n' > "$RD/a.s"
sh rakit.sh "$RD/a.s" "$RD/keluar" >/dev/null 2>&1
RX="$RD/keluar"
cek "rakit program keluar 7" "$("$RX" >/dev/null; echo $?)"  "7"
printf '_start:\n    mov x0, #0\n    mov x1, #5\nulang:\n    add x0, x0, #3\n    sub x1, x1, #1\n    cbz x1, selesai\n    b ulang\nselesai:\n    mov x8, #93\n    svc #0\n' > "$RD/b.s"
sh rakit.sh "$RD/b.s" "$RD/jumlah" >/dev/null 2>&1
RJ="$RD/jumlah"
cek "rakit loop dan cabang"  "$("$RJ"; echo $?)"  "15"
printf '_start:\n    b ada\n' > "$RD/c.s"
cek "rakit label tak ada"    "$(sh rakit.sh "$RD/c.s" "$RD/x" 2>&1 | sed -n 2p)"  "!! baris 2: label tidak ada: ada"
printf '_start:\n    foo x0\n' > "$RD/c.s"
cek "rakit instruksi asing"  "$(sh rakit.sh "$RD/c.s" "$RD/x" 2>&1 | sed -n 2p)"  "!! baris 2: instruksi belum didukung: foo"
cek "rakit tanpa argumen"    "$(sh rakit.sh 2>&1 | head -c 5)"  "pakai"
rm -rf "$RD"
[ $gagal = 0 ] && echo "SEMUA TES LULUS" || echo "ADA TES GAGAL"
exit $gagal
